//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Details
    {
        [Key]
        public string carId { get; set; }
        public string CC { get; set; }
        public string kwFrom { get; set; }
        public string kwTo { get; set; }
        public string HpFrom { get; set; }
        public string HpTo { get; set; }
        public string AnneeDe { get; set; }
        public string AnneeA { get; set; }
        public string Carrosserie { get; set; }
        public Nullable<int> valves { get; set; }
        public Nullable<int> cylinder { get; set; }
        public string CodeMoteur { get; set; }
        public string TypeCarburant { get; set; }
        public string CarburantProcess { get; set; }
        public Nullable<System.DateTime> Date_Dev { get; set; }
        public Nullable<System.DateTime> Date_Dev2 { get; set; }
    }
}
