//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Images
    {
        [Key]
        public int docId { get; set; }
        public string docFileName { get; set; }
        public Nullable<int> docTypeId { get; set; }
        public string docTypeName { get; set; }
        public int articleId { get; set; }
    }
}
