//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Log
    {
        [Key]
        public int idLog { get; set; }
        public string tableName { get; set; }
        public string operation { get; set; }
        public string userName { get; set; }
        public System.DateTime dateTime { get; set; }
        public string clePrimU { get; set; }
        public string clePrimD { get; set; }
        public string clePrimT { get; set; }
        public string ancienneValeur { get; set; }
        public string nouvelleValeur { get; set; }
        public string champs { get; set; }
    }
}
