//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PARCAR
    {
         [Key]
         public int idParc { get; set; }
        public string Serie { get; set; }
        public string P { get; set; }
        public string PROP { get; set; }
        public string VEHIC_TYPE { get; set; }
        public string No1 { get; set; }
        public int EntryVin { get; set; }
        public string FABR { get; set; }
        public string COL7 { get; set; }
        public string CV { get; set; }
        public string Poids { get; set; }
        public string NB_places { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public Nullable<int> JJ1 { get; set; }
        public Nullable<int> MM1 { get; set; }
        public Nullable<int> AA1 { get; set; }
        public Nullable<int> JJ2 { get; set; }
        public Nullable<int> MM2 { get; set; }
        public Nullable<int> AA { get; set; }
        public Nullable<decimal> Poids_net { get; set; }
        public string Racine_série { get; set; }
        public Nullable<int> Série1 { get; set; }
        public Nullable<int> Série2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Info_Développement_1 { get; set; }
        public string Info_Développement_2 { get; set; }
        public string Type_carrosserie { get; set; }
        public string Projet { get; set; }
        public string Projet2 { get; set; }
        public string Année_d_émission { get; set; }
        public string Energie { get; set; }
        public Nullable<byte> AlerteVin { get; set; }
        public string VDS { get; set; }
        public string ID_FABR { get; set; }
        public string Cylindré { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
