//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [Key]
        public int EntryVin { get; set; }
        public string VIN { get; set; }
        public string manuId { get; set; }
        public string modelId { get; set; }
        public string carId { get; set; }
        public string vehicleTypeDescription { get; set; }
        public string carName { get; set; }
        public Nullable<int> Load_Type { get; set; }
    }
}
